[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "pnpm run dev"
  port = 3000
  publish = ".next"
